### ISSUE TITLE
pyyaml security alert

### ISSUE THREAD

**Issue by troy2914** [irrdnet/irrd4#162]
GitLab is warning about a potential security hole in pyyaml.

Related to the non-safe use of load(), though we are using the safe_load()

Also interesting to note it has not been flagged/picked up by the weekly updates.

**Comment by mxsasha** [comment]
Yes, I've noticed this. I think pyup may not have picked it up because the fixed version of pyyaml seems to be a beta version, which is also why I haven't upgraded the dependency yet.

We use safe_load() consistently indeed, and even using the unsafe load() would have a limited impact as we only read config files, not user entered data. I also thought the default-unsafe of load() was a "feature" for as long as I can remember, so it's possible pyup does not consider it a vulnerability.

The vulnerability alert isn't visible to everyone btw, only people with certain access to the project. I'm inclined to leave this as is until a non-beta release is made of the "fixed" pyyaml version.

**Comment by troy2914** [comment]
PyYAML has been updated 5.1
