### ISSUE TITLE
Missing one or more route-objects?

### ISSUE THREAD

**Issue by job** [irrdnet/irrd4#187]
For some reason this route object is missing 

```
route:      103.237.54.0/23
descr:      Layer42 Networks
origin:     AS8121
mnt-by:     MAINT-AS8121
changed:    noc@layer42.net 20140716
source:     ALTDB
```

```
hanna:~ job$ whois -h irrd01.ip.gin.ntt.net '!jALTDB'
A20
ALTDB:Y:48227-49466
C
hanna:~ job$ curl ftp://ftp.altdb.net/pub/altdb/ALTDB.CURRENTSERIAL
49466
```

I don't see anything wrong with the object, or why it wasn't imported.

**Comment by mxsasha** [comment]
I don't see this object at all in ftp://ftp.altdb.net/pub/altdb/altdb.db.gz. I see it on rr.ntt.net, so perhaps this is an IRRDv2 bug?

On a sidenote, as part of debugging this, I did a forced reload of ALTDB, and note the following log:
```Ignored 9 objects found in file import for ALTDB due to unknown object classes: *xx-num, poem, ipv6-site, limerick, poetic-form, *xxte6, *xxner, *xxte-set, irt, *xxson, *xxe, organisation, *xxset, *xxte```

Some are unimportant, but the *xxte object may mean that ALTDB incorrect wrote out a route to their dump, which can not be imported. So it is possible that a route is missing, because it was never recorded in the dump in the proper syntax. But I'm not seeing this prefix at all in the current dump. So I don't think it explains this particular situation.

**Comment by job** [comment]
woah.... RADB also has that object.

```
hanna:~ job$ whois -h whois.radb.net -- "-sALTDB 103.237.54.0/23"
route:      103.237.54.0/23
descr:      SRDF Inc
origin:     AS395372
mnt-by:     MAINT-AS395372
changed:    noc@rubinbroadcasting.com 20160716
source:     ALTDB

route:      103.237.54.0/23
descr:      Layer42 Networks
origin:     AS8121
mnt-by:     MAINT-AS8121
changed:    noc@layer42.net 20140716
source:     ALTDB
```

I refreshed ALTDB on `rr.ntt.net` and the route is gone now
