### ISSUE TITLE
Let irrd_load_database do more work

### ISSUE THREAD

**Issue by job** [irrdnet/irrd4#233]
**Is your feature request related to a problem? Please describe.**
Right now I have to provide a gunzipped dump and serial to the `irrd_load_database` tool, but the tool could also download the dump & serial based on the URL known in the yml config.

**Describe the solution you'd like**

```
$ grep -A6 RIPE: /etc/irrd.yaml | grep import
            import_serial_source: ftp://ftp.ripe.net/ripe/dbase/RIPE.CURRENTSERIAL
            import_source: ftp://ftp.ripe.net/ripe/dbase/ripe.db.gz
$ irrd_load_database -s RIPE   # the tool can fetch & gunzip & fetch serial itself based on the config
   ... 
```

**Describe alternatives you've considered**
Flipping a flag in the database?

**Comment by mxsasha** [comment]
I'm curious about your usecase. This is basically something the force_reload flag already does. We can add a command to set that flag for a source?

The load_database command was intended for script-generated databases, i.e. those that update relatively rarely, and need stricter validation than regular mirrors. I think it would also refuse to import RIPE, because of unknown object classes. The load_database command is quite strict, as for errors the assumption is "the script generating that file made a mistake" vs "do a best effort import of valid data" for regular mirrors.

**Comment by job** [comment]
Yes, i guess my request is to add a CLI command to set the `force_reload` flag so we don't need operations to connect directly to the database. Perhaps some luxury such as progress bar would be nice too.

**Comment by mxsasha** [comment]
The behaviour of the new command is now documented in: https://irrd4.readthedocs.io/en/latest/users/mirroring.html#nrtm-mode

Progress bars are difficult - the actual reload happens asynchronously. The command just flips the flag in the DB, the next run of the importer for that source reads it and acts on it.

**Comment by job** [comment]
this works as advertised!
