### ISSUE TITLE
priority: test whether irrd4 and post-NWI5 RIPE DB play nice

### ISSUE THREAD

**Issue by job** [irrdnet/irrd4#86]
RIPE NCC's IRR is about to split into two sources, each their own NRTM and IRR source.

We should verify whether the current IRRd v4 code can deal with what the current Release Candidate is.

dumps at https://ftp.ripe.net/ripe/dbase/rc/

**Comment by mxsasha** [comment]
This is verified to work, and the files and NRTM stream are split correctly by source.

There is a peculiarty though: the NRTM serials of both streams are linked. Submitting a new update to RIPE will advance the serial counter of RIPE-NONAUTH, and vice versa. This causes some side effects, though IRRD4 can handle them.

Usually, when querying for a serials that do (not yet) exist, a typical response is:
```
%ERROR:401: invalid range: Not within 2278326-42432633
```

However, because the serials between RIPE and RIPE-NONAUTH are linked, the source that the serial does not belong to, can send a valid start line with then an empty NRTM response:

`-g RIPE-NONAUTH:3:42432634-LAST`:
```
%START Version: 3 RIPE-NONAUTH 42432634-42432635

%END RIPE-NONAUTH
```

`-g RIPE:3:42432634-LAST`
```
%START Version: 3 RIPE 42432634-42432635

ADD 42432634

route:          192.106.250.0/24
descr:          test 1
origin:         AS1267
mnt-by:         AS1267-MNT
created:        1970-01-01T00:00:00Z
last-modified:  2018-08-20T10:04:01Z
source:         RIPE
remarks:        ****************************
remarks:        * THIS OBJECT IS MODIFIED
remarks:        * Please note that all data that is generally regarded as personal
remarks:        * data has been removed from this object.
remarks:        * To view the original object, please query the RIPE Database at:
remarks:        * http://www.ripe.net/whois
remarks:        ****************************

ADD 42432635

route:          192.106.250.0/24
descr:          test 2
origin:         AS1267
mnt-by:         AS1267-MNT
created:        1970-01-01T00:00:00Z
last-modified:  2018-08-20T10:04:08Z
source:         RIPE
remarks:        ****************************
remarks:        * THIS OBJECT IS MODIFIED
remarks:        * Please note that all data that is generally regarded as personal
remarks:        * data has been removed from this object.
remarks:        * To view the original object, please query the RIPE Database at:
remarks:        * http://www.ripe.net/whois
remarks:        ****************************

%END RIPE
```

IRRD4 can deal with this due to #85 where we allow non-sequential serials, and therefore also NRTM responses that mention serials in the START line, but then have no ADD/DEL operations attached to them.
